name: sweater
description: Sweater
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: '>=4.0.0 <5.0.0'
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  csv: ^5.0.2
  rxdart: ^0.27.7
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  geolocator: ^9.0.2
  xml: ^6.2.2
  xml2json: ^5.3.6
  get_it: ^7.6.0
  flutter_spinkit: ^5.2.0
  logger: ^2.4.0
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  test: ^1.24.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/data/
    - assets/images/
